#!/bin/python3

import math
import os
import random
import re
import sys

def time_delta(t1, t2):
    def time_delta(t1, t2):
    
    fmt = "%a %d %b %Y %H:%M:%S %z"
    
    dt1 = datetime.strptime(t1,fmt)
    dt2 = datetime.strptime(t2,fmt)
    
    k = (abs(dt1-dt2).total_seconds())
    
    return str(int(k))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        t1 = input()

        t2 = input()

        delta = time_delta(t1, t2)

        fptr.write(delta + '\n')

    fptr.close()
